// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbAvlumIxf-6QLauoeiaOWmhFmi5xaflo',
    appId: '1:1089581974859:web:05072a3a53a1f96b8054ce',
    messagingSenderId: '1089581974859',
    projectId: 'tripmate-9edb4',
    authDomain: 'tripmate-9edb4.firebaseapp.com',
    storageBucket: 'tripmate-9edb4.firebasestorage.app',
    measurementId: 'G-P4JC4GNVWF',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbAvlumIxf-6QLauoeiaOWmhFmi5xaflo',
    appId: '1:1089581974859:web:df5bb82756964e988054ce',
    messagingSenderId: '1089581974859',
    projectId: 'tripmate-9edb4',
    authDomain: 'tripmate-9edb4.firebaseapp.com',
    storageBucket: 'tripmate-9edb4.firebasestorage.app',
    measurementId: 'G-5KFQYC2HHL',
  );

}